made it to work with single ipython notebook, probably older version.
vlad17/IPython-2to3 pull request #1
Opened 2016-12-22 06:44 UTC by shimondoodkin

had a problem converting workbook of cs231n assignment1. so I made it work for it

2016-12-22 07:53 UTC, vlad17 commented
Thanks for the PR. Would you mind addressing my comments on it? Then I can merge it in.

2016-12-22 11:51 UTC, shimondoodkin commented
what comments?

2016-12-22 17:13 UTC, vlad17 requested changes

2016-12-22 17:13 UTC, vlad17 commented on ipy2to3_other.py
> +            cmd2to3 = ["C:/Anaconda3_64/Scripts/2to3.exe", "--nobackups", "--write", file_name]
This invocation is going to only work for windows and Anaconda users - it'll break for everyone else

2016-12-22 17:13 UTC, vlad17 commented on ipy2to3_other.py
> +#!/usr/bin/env python3
Why make this a completely new file? Can't you put them all into the original one?

2016-12-22 17:13 UTC, vlad17 commented on ipy2to3_other.py
> +    #for worksheet in json_to_convert['worksheets']:
Why did you comment this out?

2016-12-22 19:13 UTC, shimondoodkin commented on ipy2to3_other.py
> +#!/usr/bin/env python3
looks like it is a different application. it is not better. it is for different version of ipython

2016-12-22 19:13 UTC, shimondoodkin commented on ipy2to3_other.py
> +    #for worksheet in json_to_convert['worksheets']:
this version of ipython had no worksheets

2016-12-22 19:14 UTC, shimondoodkin commented on ipy2to3_other.py
> +            cmd2to3 = ["C:/Anaconda3_64/Scripts/2to3.exe", "--nobackups", "--write", file_name]
i left it as an example for others to change to their python

2016-12-22 19:19 UTC, vlad17 commented on ipy2to3_other.py
> +#!/usr/bin/env python3
Right, but having the file called ipy2to3_other.py is confusing to people who want to use the tool. It is better to have one file that then is smart enough to decide what code it should be using from the ipython version.

2016-12-22 19:20 UTC, vlad17 commented on ipy2to3_other.py
> +    #for worksheet in json_to_convert['worksheets']:
What version? Can you just put an if-else in the original file that intelligently switches between the two. As it stands, you're making the user have to figure it out themselves (by choosing between ipy2to3 and ipy2to3_other.

2016-12-22 19:21 UTC, shimondoodkin commented
i converted the assignment1 of cs231n

https://www.stanfordterminalcloud.com/snapshot/49f5a1ea15dc424aec19155b3398784d57c55045435315ce4f8b96b62819ef65

http://cs231n.github.io

the command like 2to3 -w in that directory worked fine. just had to add latin1 in the loader. pickle.load(f, encoding='latin')

2016-12-22 19:21 UTC, vlad17 commented on ipy2to3_other.py
> +            cmd2to3 = ["C:/Anaconda3_64/Scripts/2to3.exe", "--nobackups", "--write", file_name]
If that's the case then I'd suggest using the original '2to3' on its own which is less confusing and less specific to windows users

2016-12-22 19:25 UTC, shimondoodkin commented
you can. see yourself the files are similar but different seems like of an older version.
maybe it is possible to detect older version if there are no worksheets then also to not require language=python if then

2016-12-27 04:57 UTC, vlad17 commented
I'm not quite sure what you mean. But I agree, it can be pretty easy to just check "if 'worksheets' not in json" then to proceed without the worksheet extraction. But then this logic should be in the original file.

2016-12-27 05:46 UTC, shimondoodkin commented
yes i'm kind of with you on the idea of single file

On Tue, Dec 27, 2016 at 6:57 AM, Vladimir Feinberg <notifications@github.com
> wrote:

> I'm not quite sure what you mean. But I agree, it can be pretty easy to
> just check "if 'worksheets' not in json" then to proceed without the
> worksheet extraction. But then this logic should be in the original file.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vlad17/IPython-2to3/pull/1#issuecomment-269269989>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AATMYBCmzlSXIlMPrdhuRZwohsf2E0LXks5rMJrUgaJpZM4LTsEv>
> .
>

2016-12-27 06:53 UTC, shimondoodkin commented
made the changes

2016-12-27 08:11 UTC, vlad17 requested changes

2016-12-27 08:11 UTC, vlad17 commented on ipy2to3.py
> +        cell['source' if version is "old" else 'input'] = istream.readlines()
These should be 'input' now because python3 is only for the new version, even if the original was 'source', right?

2016-12-27 08:11 UTC, vlad17 commented on ipy2to3.py
> +        cell['source' if version is "old" else 'input'][i] = line
same

2016-12-27 08:11 UTC, vlad17 commented on ipy2to3.py
> +def convert_ipy2to3(json_to_convert):
can you pass filename in by argument here? instead of using argv.

2016-12-27 08:16 UTC, shimondoodkin commented on ipy2to3.py
> +        cell['source' if version is "old" else 'input'] = istream.readlines()
no it works ok, it does not convert ipython version just the python version

2016-12-27 08:27 UTC, shimondoodkin commented
look now

2016-12-27 17:23 UTC, vlad17 requested changes
almost done. one more thing.

2016-12-27 17:23 UTC, vlad17 commented on ipy2to3.py
> +        return 0
return 1 if there was an error

2016-12-27 22:21 UTC, shimondoodkin commented
look

2016-12-28 16:30 UTC, vlad17 commented
OK. Have you tested it? Does it still work?

2016-12-29 04:40 UTC, vlad17 commented
Unless you plan on adding automated testing, there's no need to have the testing files directly; we can have manual testing for now, but without random test files. Please remove them, and then we can merge.

2016-12-29 19:28 UTC, shimondoodkin commented
yes tested it works well

2016-12-30 00:43 UTC, vlad17 commented
Yes, manual tests are good, but please REMOVE the *.ipynb files from the PR. They are confusing, large, and difficult to maintain - only keep the `ipy2to3.py` file.

2016-12-30 03:32 UTC, shimondoodkin commented
if i remove them how would you test it later?

2016-12-30 04:02 UTC, vlad17 commented
It is hard to run manual tests, especially with files they aren't familiar with. The new files, as I mentioned, are also large and add clutter, regardless of their use in testing. If you really want them there, I suggest adding them through an automated unit testing framework. But that really seems like overkill to me. This should just be a simple script.

2016-12-30 06:51 UTC, shimondoodkin commented
how do you suggest to develop tests?

2016-12-30 16:29 UTC, merged

2016-12-30 16:29 UTC, vlad17 commented
Nice, thank you!